/usr/bin/uuidgen: /apps/spack/gilbreth/apps/anaconda/2020.11-py38-gcc-4.8.5-djkvkvk/lib/libuuid.so.1: no version information available (required by /usr/bin/uuidgen)
/home/vciroski/.local/lib/python3.8/site-packages/pydot.py:17: UserWarning: `pydot` could not import `dot_parser`, so `pydot` will be unable to parse DOT files. The error was:  No module named 'pyparsing'
  warnings.warn(
Traceback (most recent call last):
  File "langchain_hard.py", line 558, in <module>
    file_contents= image_to_text_tool._run()
TypeError: _run() missing 1 required positional argument: 'urls'
srun: error: gilbreth-k035: task 0: Exited with exit code 1
